#######################################
### Bash Settings File :: ~/.bashrc ###
#######################################
#
# Reload this file:
# $ . ~/.bashrc
#

### If not running interactively, don't do anything
[[ $- != *i* ]] && return

###
### Bash Options
###

##
## Changing Directories
##

# Type directory names to cd into them
shopt -s autocd

# Change directories into variable names (with directory values)
shopt -s cdable_vars

# Autocorrect misspelled directory names when using cd
shopt -s cdspell

##
## Command History
##

# Remove command history limit
unset HISTSIZE
export HISTSIZE

# Remove ~/.bash_history line limit
unset HISTFILESIZE
export HISTFILESIZE

# Remove duplicate commands and commands starting with a space
export HISTCONTROL=ignoreboth:erasedups

# Append commands to ~/.bash_history instead of overwriting it
shopt -s histappend

# Store multi-line commands as a single command
shopt -s cmdhist

# Disable flow control to enable forward search history
[[ $- == *i* ]] && stty -ixon

# Share history across all terminals
export PROMPT_COMMAND="history -n; history -w; history -c; history -r; $PROMPT_COMMAND"
#PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"

##
## Modifications to $PATH
##

# RubyGems
PATH="$(ruby -e 'print Gem.user_dir')/bin:$PATH"

# Export all modifications
export PATH

##
## Colorization
##

# Colorize directory contents a bit more
eval $(dircolors --bourne-shell)

##
## Default Programs
##

export EDITOR=gvim
export PAGER=less

##
## Misc. Options
##

# Check hashtable before running command, then check $PATH
shopt -s checkhash

# Update $LINES and $COLUMNS after each command (if altered)
shopt -s checkwinsize

# Get immediate notification if a background job was terminated
set -o notify

###
### Prompt
###

# Color variables
green=$(tput setaf 2)
blue=$(tput setaf 4)
reset=$(tput sgr0)

# Default
# PS1='[\u@\H \W]\$ '

# Basic
# PS1='\u@\H \w\$ '

# Fancy
PS1='\u@\H [\[$green\]\w\[$reset\]] \[$blue\]➜\[$reset\] '

###
### Aliases
###

##
## Modified existing commands
##

alias grep='grep --color=auto --line-number --ignore-case'
alias mkdir='mkdir --verbose --parents'
alias diff='colordiff --side-by-side --report-identical-files'
alias df='df --human-readable --print-type --total'
alias dfa='df --all'
alias dfc='dfc -d -s -T -w -W'
alias dfca='dfc -a'
alias du='du --human-readable --total'
alias dmesg='dmesg --color'
alias ip='ip -color -human-readable'
alias nano='nano --nowrap'
alias vi='/usr/bin/vim'
alias vim='gvim'
alias pactree='pactree --color'

# ls
alias ls='ls --color=auto --classify --human-readable --group-directories-first --literal'
alias lr='ls --recursive'
alias ll='ls -l'
alias la='ll --almost-all'
alias lm='la | less'

# Sorting with ls
alias lx='ll --ignore-backups -X' # Sort by extension
alias lz='ll --reverse -S'        # Sort by size
alias lt='ll --reverse -t'        # Sort by date

# Safety checks on critical commands
alias mv='mv --verbose --interactive'
alias cp='cp --verbose --interactive'
alias ln='ln --verbose --interactive'
alias rm='rm --verbose --interactive=once'
# alias rm=' timeout 3 rm -Iv --one-file-system' # Even safer
alias rmdir='rmdir --verbose'
alias chown='chown --preserve-root'
alias chmod='chmod --preserve-root'
alias chgrp='chgrp --preserve-root'

# Error tolerance
alias sl='ls'
alias ks='ls'
alias cd..='cd ..'

##
## New commands
##

#alias ..='cd ..' # Not necessary when autocd is enabled
alias off='systemctl poweroff'
#alias off='shutdown --poweroff now' # Works without systemd; symlink to above command on Arch
alias hdate='date "+%A, %B %d, %Y [%I:%M:%S %p]"'
alias please='sudo `fc -n -l -1`'

# Network Analysis
alias pong='ping -c 3 8.8.8.8'
alias pong2='ping -c 3 www.google.com'
alias intip='echo -n "Internal IP Address(es): "; hostname --ip-addresses'
alias extip='echo -n "External IP Address: "; curl https://icanhazip.com/'

# Searching with grep
alias dm='dmesg | grep'
alias hist='history | grep'
alias pss='ps -aux | grep'

# pacman
alias up='sudo pacman --sync --refresh --sysupgrade'
alias upp='sudo pacman --sync --refresh --refresh --sysupgrade'
alias pacr='sudo pacman --sync --refresh --refresh'
alias pacc='sudo pacman --sync --clean'
alias pacclean='sudo pacman --sync --clean --clean'
alias pacs='pacman --sync --search'
alias pacsl='pacman --query --search'

# pacman-related
alias mirrorlist='sudo reflector --verbose --latest 5 --sort rate --save /etc/pacman.d/mirrorlist'
alias pacnew='find /etc -regextype posix-extended -regex ".+\.pac(new|save)" 2> /dev/null'
alias pacnew2='sudo updatedb && locate --existing --regex "\.pac(new|save)$"'
alias pacnewlog='grep --extended-regexp "pac(new|save)" /var/log/pacman.log | tail'

###
### Functions
###

##
## Colorize man pages
##
#
# References:
# https://wiki.archlinux.org/index.php/Man_page#Colored_man_pages
# https://linuxtidbits.wordpress.com/2009/03/23/less-colors-for-man-pages/
# https://en.wikipedia.org/wiki/ANSI_escape_code
#
man() {
    env LESS_TERMCAP_mb=$'\E[33m' \
    LESS_TERMCAP_md=$'\E[1;31m' \
    LESS_TERMCAP_me=$'\E[0m' \
    LESS_TERMCAP_se=$'\E[0m' \
    LESS_TERMCAP_so=$'\E[7m' \
    LESS_TERMCAP_ue=$'\E[0m' \
    LESS_TERMCAP_us=$'\E[1m' \
    man "$@"
}

##
## Home Screen (runs every time an interactive shell is opened)
##
homescreen() {
    fortune -a
}

###
### Home Screen
###

homescreen

